# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DroneCommander' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DroneCommander
  pod 'DJI-SDK-iOS', '~> 4.0’
  pod 'DJI-UILibrary-iOS', '~> 4.4'
  pod 'UIView+draggable'

end
